#!/bin/bash
# ======================================================
# BBANTU SAFE PATCH v2 – With automatic backups
# ======================================================

set -e

echo "📦 Applying Bbantu Safe Patch..."

# ---- BACKUP EXISTING EDGE FUNCTIONS ----
if [ -f "supabase/functions/confirm-payment/index.ts" ]; then
  mkdir -p .patch-backups
  cp supabase/functions/confirm-payment/index.ts .patch-backups/confirm-payment.backup.$(date +%s).ts
  echo "✅ Backed up: confirm-payment/index.ts"
fi

if [ -f "supabase/functions/create-order/index.ts" ]; then
  mkdir -p .patch-backups
  cp supabase/functions/create-order/index.ts .patch-backups/create-order.backup.$(date +%s).ts
  echo "✅ Backed up: create-order/index.ts"
fi

# ---- 1. SQL Migration ----
mkdir -p supabase/migrations
cat > supabase/migrations/audit_fixes.sql << 'EOF'
-- ============================================================
-- BBANTU AUDIT FIXES – P0 & P1
-- Run this once in Supabase SQL Editor
-- ============================================================

-- 1. INDEXES (Performance)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_access_token ON orders(access_token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_admin_users_id ON admin_users(id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- 2. ADD IDEMPOTENCY KEY (Prevent duplicate submissions)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS idempotency_key text UNIQUE;

-- 3. ADD HASHED TOKEN COLUMN (Security)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS access_token_hash text;
UPDATE orders SET access_token_hash = encode(sha256(access_token::bytea), 'hex') 
WHERE access_token_hash IS NULL AND access_token IS NOT NULL;

-- 4. RATE LIMITING TABLE
CREATE TABLE IF NOT EXISTS rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip inet NOT NULL,
  action text NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rate_limits_ip_action_created 
ON rate_limits(ip, action, created_at DESC);

ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role can do anything" ON rate_limits
  USING (true)
  WITH CHECK (true);

-- 5. STOCK DECREMENT FUNCTION (ADAPT THIS TO YOUR ACTUAL STOCK TABLE)
-- Run this query to find your stock table:
-- SELECT table_name, column_name FROM information_schema.columns WHERE column_name LIKE '%stock%' OR column_name LIKE '%quantity%';
CREATE OR REPLACE FUNCTION decrement_stock(p_variant_id uuid, p_quantity integer)
RETURNS void AS $$
BEGIN
  -- ⚠️ ADAPT THIS LINE TO YOUR ACTUAL STOCK TABLE ⚠️
  UPDATE inventory 
  SET quantity = quantity - p_quantity 
  WHERE variant_id = p_variant_id AND quantity >= p_quantity;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Insufficient stock for variant %', p_variant_id;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 6. CLEANUP FUNCTION
CREATE OR REPLACE FUNCTION clean_rate_limits() RETURNS void AS $$
BEGIN
  DELETE FROM rate_limits WHERE created_at < now() - interval '1 day';
END;
$$ LANGUAGE plpgsql;
EOF
echo "✅ Created SQL migration: supabase/migrations/audit_fixes.sql"

# ---- 2. Edge Function: confirm-payment ----
mkdir -p supabase/functions/confirm-payment
cat > supabase/functions/confirm-payment/index.ts << 'EOF'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0';

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  { auth: { persistSession: false } }
);

async function requireAdmin(req: Request, requiredPermission: string) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) throw new Error('Unauthorized');
  const token = authHeader.replace('Bearer ', '');
  
  const { data: user, error } = await supabase.auth.getUser(token);
  if (error || !user) throw new Error('Invalid token');

  const { data: admin, error: adminErr } = await supabase
    .from('admin_users')
    .select('*')
    .eq('id', user.user.id)
    .single();

  if (adminErr || !admin) throw new Error('Not an admin');

  const permissionMap: Record<string, string> = {
    verify_payments: 'can_verify_payments',
    scan_pickup: 'can_scan_confirm_pickup',
  };
  const permColumn = permissionMap[requiredPermission];
  if (!permColumn || admin[permColumn] !== true) {
    throw new Error(`Insufficient permissions for ${requiredPermission}`);
  }
  return admin;
}

async function decrementStock(variantId: string, quantity: number): Promise<void> {
  const { error } = await supabase.rpc('decrement_stock', {
    p_variant_id: variantId,
    p_quantity: quantity
  });
  if (error) throw new Error(`Stock decrement failed: ${error.message}`);
}

Deno.serve(async (req) => {
  try {
    await requireAdmin(req, 'verify_payments');

    const { orderId, idempotencyKey } = await req.json();
    if (!orderId) throw new Error('Missing orderId');

    if (idempotencyKey) {
      const { data: existing } = await supabase
        .from('orders')
        .select('id')
        .eq('idempotency_key', idempotencyKey)
        .single();
      if (existing) {
        return new Response(JSON.stringify({ success: true, message: 'Already processed', orderId }), { status: 200 });
      }
    }

    const { data: order, error: orderErr } = await supabase
      .from('orders')
      .select(`id, status, order_items ( variant_id, quantity )`)
      .eq('id', orderId)
      .single();

    if (orderErr || !order) throw new Error('Order not found');
    if (order.status !== 'awaiting_payment') throw new Error('Order already processed');

    for (const item of order.order_items) {
      await decrementStock(item.variant_id, item.quantity);
    }

    const { error: updateErr } = await supabase
      .from('orders')
      .update({ status: 'paid', idempotency_key: idempotencyKey || null })
      .eq('id', orderId)
      .eq('status', 'awaiting_payment');

    if (updateErr) throw updateErr;

    return new Response(JSON.stringify({ success: true, orderId, message: 'Payment confirmed' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Confirm payment error:', error);
    const status = error.message.includes('Unauthorized') ? 401 :
                   error.message.includes('permissions') ? 403 : 500;
    return new Response(JSON.stringify({ error: error.message || 'Internal error' }), {
      status,
      headers: { 'Content-Type': 'application/json' }
    });
  }
});
EOF
echo "✅ Updated Edge Function: supabase/functions/confirm-payment/index.ts"

# ---- 3. Edge Function: create-order ----
mkdir -p supabase/functions/create-order
cat > supabase/functions/create-order/index.ts << 'EOF'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0';

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  { auth: { persistSession: false } }
);

async function checkRateLimit(ip: string, action: string, limit = 5, windowSeconds = 60) {
  const cutoff = new Date(Date.now() - windowSeconds * 1000).toISOString();
  const { count, error } = await supabase
    .from('rate_limits')
    .select('id', { count: 'exact', head: true })
    .eq('ip', ip)
    .eq('action', action)
    .gte('created_at', cutoff);
  if (error) throw error;
  if (count && count >= limit) throw new Error('Too many requests. Please wait.');
}

async function recordRateLimit(ip: string, action: string) {
  await supabase.from('rate_limits').insert({ ip, action });
}

async function hashToken(rawToken: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(rawToken);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

Deno.serve(async (req) => {
  try {
    const ip = req.headers.get('x-forwarded-for')?.split(',')[0] || 'unknown';
    await checkRateLimit(ip, 'create_order', 5, 60);
    await recordRateLimit(ip, 'create_order');

    const { customer_id, items, shipping_address, payment_type, sales_mode, fulfilment_method } = await req.json();
    if (!items || !items.length) throw new Error('No items');

    const variantIds = items.map((i: any) => i.variant_id);
    const { data: variants, error: variantsErr } = await supabase
      .from('product_variants')
      .select('id, price')
      .in('id', variantIds);
    if (variantsErr || !variants) throw new Error('Failed to fetch product data');

    let subtotal = 0;
    const orderItems = items.map((item: any) => {
      const variant = variants.find(v => v.id === item.variant_id);
      if (!variant) throw new Error(`Variant ${item.variant_id} not found`);
      const subtotalItem = Number(variant.price) * item.quantity;
      subtotal += subtotalItem;
      return { variant_id: item.variant_id, quantity: item.quantity, price_at_time: variant.price };
    });

    const shippingCost = 0; // Compute or fetch from shipping API
    const rawToken = crypto.randomUUID();
    const tokenHash = await hashToken(rawToken);

    const { data: order, error: orderErr } = await supabase
      .from('orders')
      .insert({
        customer_id,
        sales_mode,
        payment_type,
        fulfilment_method: fulfilment_method || null,
        merchandise_subtotal: subtotal,
        shipping_cost: shippingCost,
        amount_paid: subtotal + shippingCost,
        status: 'awaiting_payment',
        access_token: rawToken,      // Temporary - will be phased out
        access_token_hash: tokenHash,
        access_token_encrypted: null,
        created_at: new Date().toISOString(),
      })
      .select('id')
      .single();

    if (orderErr) throw orderErr;

    const orderItemsWithId = orderItems.map(item => ({ ...item, order_id: order.id }));
    const { error: itemsErr } = await supabase.from('order_items').insert(orderItemsWithId);
    if (itemsErr) throw itemsErr;

    return new Response(JSON.stringify({
      success: true,
      orderId: order.id,
      token: rawToken,
      trackingUrl: `${Deno.env.get('APP_URL')}/track?token=${rawToken}`
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Create order error:', error);
    const status = error.message.includes('Too many') ? 429 : 500;
    return new Response(JSON.stringify({ error: error.message || 'Internal error' }), {
      status,
      headers: { 'Content-Type': 'application/json' }
    });
  }
});
EOF
echo "✅ Updated Edge Function: supabase/functions/create-order/index.ts"

# ---- 4. Frontend: Admin Realtime Hook ----
mkdir -p src/hooks
cat > src/hooks/useAdminRealtime.ts << 'EOF'
import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

type Notification = {
  id: string;
  type: 'new_order' | 'payment_uploaded';
  message: string;
  orderId: string;
  timestamp: Date;
};

export function useAdminRealtime() {
  const [notifications, setNotifications] = useState<Notification[]>([]);

  useEffect(() => {
    const orderChannel = supabase
      .channel('admin-orders')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'orders' }, (payload) => {
        const newOrder = payload.new as any;
        setNotifications(prev => [{
          id: crypto.randomUUID(),
          type: 'new_order',
          message: `📦 New order #${newOrder.order_number || newOrder.id.slice(0, 8)}`,
          orderId: newOrder.id,
          timestamp: new Date()
        }, ...prev]);
      })
      .subscribe();

    const paymentChannel = supabase
      .channel('admin-payments')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'payment_proofs' }, (payload) => {
        const newProof = payload.new as any;
        setNotifications(prev => [{
          id: crypto.randomUUID(),
          type: 'payment_uploaded',
          message: `💳 Payment uploaded for order #${newProof.order_id.slice(0, 8)}`,
          orderId: newProof.order_id,
          timestamp: new Date()
        }, ...prev]);
      })
      .subscribe();

    return () => {
      supabase.removeChannel(orderChannel);
      supabase.removeChannel(paymentChannel);
    };
  }, []);

  const clearAll = () => setNotifications([]);
  const dismiss = (id: string) => setNotifications(prev => prev.filter(n => n.id !== id));

  return { notifications, clearAll, dismiss };
}
EOF
echo "✅ Created frontend hook: src/hooks/useAdminRealtime.ts"

# ---- 5. Frontend: File Validation Utility ----
mkdir -p src/utils
cat > src/utils/validateFile.ts << 'EOF'
export function validatePaymentProof(file: File): { valid: boolean; error?: string } {
  const MAX_SIZE = 2 * 1024 * 1024;
  if (file.size > MAX_SIZE) return { valid: false, error: 'File too large (max 2MB).' };
  const allowedTypes = ['image/jpeg', 'image/png', 'image/webp'];
  if (!allowedTypes.includes(file.type)) return { valid: false, error: 'Only JPEG, PNG, or WEBP images are allowed.' };
  return { valid: true };
}

export async function checkMagicBytes(file: File): Promise<boolean> {
  const buffer = await file.slice(0, 4).arrayBuffer();
  const bytes = new Uint8Array(buffer);
  const hex = Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join(' ');
  return hex.startsWith('ff d8 ff') || hex.startsWith('89 50 4e 47') || hex.startsWith('52 49 46 46');
}
EOF
echo "✅ Created frontend utility: src/utils/validateFile.ts"

# ---- 6. Frontend: API Rate Limit Handler ----
mkdir -p src/api
cat > src/api/createOrder.ts << 'EOF'
export async function createOrder(orderData: any) {
  try {
    const response = await fetch('/api/create-order', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(orderData)
    });

    if (response.status === 429) {
      const data = await response.json();
      throw new Error(data.error || 'Too many orders. Please wait.');
    }
    if (!response.ok) {
      const data = await response.json();
      throw new Error(data.error || 'Order creation failed.');
    }
    return await response.json();
  } catch (error) {
    console.error('Order creation error:', error);
    throw error;
  }
}
EOF
echo "✅ Created frontend API helper: src/api/createOrder.ts"

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "🎉 PATCH APPLIED SUCCESSFULLY!"
echo ""
echo "⚠️ YOUR ORIGINAL FILES ARE BACKED UP HERE:"
echo "   → .patch-backups/confirm-payment.backup.[timestamp].ts"
echo "   → .patch-backups/create-order.backup.[timestamp].ts"
echo "   → If something breaks, just copy these back."
echo ""
echo "📋 NEXT STEPS:"
echo "1. Run the SQL migration in Supabase SQL Editor:"
echo "   → Open supabase/migrations/audit_fixes.sql"
echo "   → Copy and execute it in Supabase"
echo ""
echo "2. ⚠️ CRITICAL: ADAPT THE STOCK DECREMENT FUNCTION"
echo "   → Find your stock table: run this in Supabase SQL:"
echo "     SELECT table_name, column_name FROM information_schema.columns"
echo "     WHERE column_name LIKE '%stock%' OR column_name LIKE '%quantity%';"
echo "   → Edit the 'UPDATE inventory' line in audit_fixes.sql to match"
echo ""
echo "3. Deploy Edge Functions:"
echo "   supabase functions deploy confirm-payment"
echo "   supabase functions deploy create-order"
echo ""
echo "4. Import the new React hooks into your admin dashboard!"
echo "════════════════════════════════════════════════════════════════════"
EOF

chmod +x apply_patch.sh