-- ============================================================
-- BBANTU AUDIT FIXES – P0 & P1
-- Run this once in Supabase SQL Editor
-- ============================================================

-- 1. INDEXES (Performance)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_access_token ON orders(access_token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_admin_users_id ON admin_users(id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- 2. ADD IDEMPOTENCY KEY (Prevent duplicate submissions)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS idempotency_key text UNIQUE;

-- 3. ADD HASHED TOKEN COLUMN (Security)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS access_token_hash text;
UPDATE orders SET access_token_hash = encode(sha256(access_token::bytea), 'hex') 
WHERE access_token_hash IS NULL AND access_token IS NOT NULL;

-- 4. RATE LIMITING TABLE
CREATE TABLE IF NOT EXISTS rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip inet NOT NULL,
  action text NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rate_limits_ip_action_created 
ON rate_limits(ip, action, created_at DESC);

ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role can do anything" ON rate_limits
  USING (true)
  WITH CHECK (true);

-- 5. STOCK DECREMENT FUNCTION (ADAPT THIS TO YOUR ACTUAL STOCK TABLE)
-- Run this query to find your stock table:
-- SELECT table_name, column_name FROM information_schema.columns WHERE column_name LIKE '%stock%' OR column_name LIKE '%quantity%';
CREATE OR REPLACE FUNCTION decrement_stock(p_variant_id uuid, p_quantity integer)
RETURNS void AS $$
BEGIN
  -- ⚠️ ADAPT THIS LINE TO YOUR ACTUAL STOCK TABLE ⚠️
  UPDATE inventory 
  SET quantity = quantity - p_quantity 
  WHERE variant_id = p_variant_id AND quantity >= p_quantity;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Insufficient stock for variant %', p_variant_id;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 6. CLEANUP FUNCTION
CREATE OR REPLACE FUNCTION clean_rate_limits() RETURNS void AS $$
BEGIN
  DELETE FROM rate_limits WHERE created_at < now() - interval '1 day';
END;
$$ LANGUAGE plpgsql;
